config/routes.rb
Clutterbox::Application.routes.draw do

  resources :users, :except => [:index, :new, :destroy]

  match 'login'    => "sessions#new"
  match 'sessions' => "sessions#create",  :via => :post
  match 'logout'   => "sessions#destroy", :via => :delete

  resources :bookmarks, :except => [:index] do
    get 'popular', :on => :collection
    resources :taggings, :only => [:create, :destroy]
  end

  resources :tags, :only   => [:index, :show]

  match 'signup'  => "users#new"
  root  :to       => "public_pages#home"

end

app/models/bookmark.rb
# == Schema Information
#
# Table name: bookmarks
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  url        :string(255)
#  notes      :string(255)
#  rating     :integer
#  private    :boolean          default(FALSE)
#  view_count :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  title      :string(255)
#

class Bookmark < ActiveRecord::Base
  attr_accessible :user_id, :url, :title, :notes, :rating, :private
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  before_save do |bookmark|
    url = URI.parse(bookmark.url)
    if(!url.scheme)
      bookmark.url = bookmark.url.insert(0, "http://")
    end
  end

  validates :user_id, presence: true
  validates :url,  presence: true
  validates :title, presence: true
  validates :rating, presence: true

  def domain
    URI.parse(url).host.gsub(/\Awww\./, "") 
  end

  def self.public
    where(:private => false)
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :bookmarks, through: :taggings

  before_save { |tag| tag.name = name.downcase }
 
  WHOLE_WORD_REGEX = /\A\w+\Z/
  validates :name, presence: true, format: { with: WHOLE_WORD_REGEX }

  def to_param
  	name
  end
end

app/models/tagging.rb
# == Schema Information
#
# Table name: taggings
#
#  id          :integer          not null, primary key
#  bookmark_id :integer
#  tag_id      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Tagging < ActiveRecord::Base
  attr_accessible :bookmark_id, :tag_id
  belongs_to :bookmark
  belongs_to :tag

  validates :bookmark_id, presence: true
  validates :tag_id,  presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)
#  last_name       :string(255)
#  username        :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessor :password_confirmation 
  attr_accessible :first_name, :last_name, :username, :email, :password, :password_confirmation
  has_secure_password
  has_many :bookmarks

  before_save { |user| user.username = username.downcase }

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  VALID_USERNAME_REGEX = /\A\w+\Z/
  validates :username, presence: true, format: { with: VALID_USERNAME_REGEX },
                       uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A.+@.+\Z/
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 5 }
  validates :password_confirmation, presence: true

  def to_param 
    username
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_current_user
  protect_from_forgery
  include SessionsHelper
  include ApplicationHelper

  private 
    def set_current_user
      @current_user = User.find_by_id(cookies[:user_id])
    end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_filter :signed_in_user, only: [:create, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update, :destroy]

  def popular
    @bookmarks = Bookmark.public.order('view_count DESC')
  end

  def show 
    @bookmark = Bookmark.find(params[:id])
    @bookmark.increment(:view_count)
    @bookmark.save
    @taggings = @bookmark.taggings
    @tag  = @bookmark.tags.build
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @current_user.bookmarks.build(params[:bookmark])
    if (@bookmark.save)
      flash[:success] = "Bookmarked!"
      redirect_to @bookmark
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @bookmark.update_attributes(params[:bookmark])
      flash[:success] = "Updated Bookmark"
      redirect_to @bookmark
    else
      render 'edit'
    end
  end

  def destroy
    @bookmark.destroy
    flash[:success] = "Removed Bookmark"
    redirect_to user_path(@current_user)
  end
  
  private

  def correct_user 
    @bookmark = @current_user.bookmarks.find_by_id(params[:id])
    redirect_to root_url if @bookmark.nil?
  end
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController

  def home
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: [:create, :destroy]

  def create
    @tag = Tag.find_or_create_by_name(params[:tag][:name])
    @tagging = @bookmark.taggings.build(tag_id: @tag.id)
    if @tagging.save
      redirect_to bookmark_path(@bookmark)
    else
      render 'bookmarks/show'
    end
  end

  def destroy
    @tagging = @bookmark.taggings.find(params[:id])
    @tagging.destroy
    redirect_to bookmark_path(params[:bookmark_id])
  end

  private

  def correct_user 
    @bookmark = @current_user.bookmarks.find_by_id(params[:bookmark_id])
    redirect_to root_url if @bookmark.nil?
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find_by_name(params[:id])
    @bookmarks = @tag.bookmarks.public
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show 
    @user = User.find_by_username(params[:id])
    #@bookmarks = @user.bookmarks.public
    @bookmarks = (signed_in? && current_user?(@user)) ? @user.bookmarks : @user.bookmarks.public
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if (@user.save)
      sign_in @user
      flash[:success] = "Welcome Clutterbox!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    #@user = @current_user
  end

  def update
    #@user = @current_user
    if @user.update_attributes(params[:user])
      flash[:success] = "Updated Account"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user_to_destroy = User.find_by_username(params[:id])
    user_to_destroy.destroy
    flash[:success] = "Removed user"
    redirect_to users_path
  end

  def correct_user 
    @user = User.find_by_username(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == @current_user
  end

  def signed_in?
    !@current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      redirect_to login_path, notice: "Please sign in." 
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:user_id] = user.id
  end

  def sign_out
    cookies.delete(:user_id)
  end
end

app/views/bookmarks/_bookmark.html.erb
<article>
  <h3>
    <%= link_to bookmark.title, bookmark.url %>
    <span class="editB">
        <%= link_to "View", bookmark_path(bookmark) %>
        <% if current_user?(bookmark.user) %>
          <%= link_to "Edit", edit_bookmark_path(bookmark) %>
          <%= link_to "Remove", bookmark_path(bookmark), method: :delete,
              data: { confirm: "Remove Bookmark?" } %>
        <% end %>
    </span>
  </h3>
  <div>      
    <%= link_to bookmark.domain, bookmark.url %>
    <span> <%= bookmark.rating %> stars </span>
  </div>
  <p>
    <%= bookmark.notes %>
  </p>
</article>

app/views/bookmarks/_bookmark_fields.html.erb
<%= render 'shared/errors', object: f.object %>
<p>
  <%= f.label :url %>
  <%= f.url_field :url, :required => true %>
</p>
<p>
  <%= f.label :title %>
  <%= f.text_field :title, :required => true %>
</p>
<p>
  <%= f.label :rating %>
  <%= select :bookmark, :rating, 1..5 %>
</p>
<p>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
</p>
<p>
  <%= f.label :private %>
  <%= f.check_box :private %>
</p>

app/views/bookmarks/_bookmark_item.html.erb
<article>
  <h3>
    <%= link_to bookmark.title, bookmark.url %>
    <span class="editB">
      <%= link_to "View", bookmark_path(bookmark) %>
    </span>
  </h3>
  <div>      
    <%= link_to bookmark.domain, bookmark.url %>
    <span> <%= bookmark.rating %> stars </span>
  </div>
  <p>
    <%= bookmark.notes %>
  </p>
</article>

app/views/bookmarks/edit.html.erb
<h1> Update Bookmark </h1>
<%= form_for(@bookmark, html: { :class => "cbxForm center med wid4"}) do |f| %>
  <%= render 'bookmark_fields', f: f %>
  <%= f.submit "Update" %>
<% end %>

app/views/bookmarks/new.html.erb
<h1> Create a Bookmark </h1>
<%= form_for(@bookmark, html: { :class => "cbxForm center med wid4"}) do |f| %>
  <%= render 'bookmark_fields', f: f %>
  <%= f.submit "Create" %>
<% end %>

app/views/bookmarks/popular.html.erb
<h1>Popular</h1>
<section id="popular_feed" class="feed">
  <%= render partial: 'bookmark_item', collection: @bookmarks, :as => :bookmark %>
</section>

app/views/bookmarks/show.html.erb
<section id="show_bookmark">
  <h1>
    <%= link_to @bookmark.title, @bookmark.url %>
  </h1>
  <h5>
    <%= link_to @bookmark.url, @bookmark.url %>
    <% if current_user?(@bookmark.user) %>
      <span class="editB">
        <%= link_to "Edit", edit_bookmark_path(@bookmark) %>
        <%= link_to "Remove", bookmark_path(@bookmark), method: :delete,
                    data: { confirm: "Remove Bookmark?" } %>
      </span>
    <% end %>
  </h5>
  <h2>
    Created by <%= link_to @bookmark.user.username, @bookmark.user %>
  </h2>
  <p id="notes">
    <%= @bookmark.notes %>
  </p>
  <article>
    <span class="rating"> <%= @bookmark.rating %> Stars </span>
    <p id="tags" class="tags">
      <%= render @taggings %>
    </p>
    <% if current_user?(@bookmark.user) %>   
      <%= form_for(@tag, url: bookmark_taggings_path(@bookmark)) do |f| %>
        <%= render 'shared/errors', object: f.object %>
        <%= f.text_field :name, required: true, placeholder: "Add New Tag"  %>
        <%= f.submit "Tag" %>
      <% end %>  
    <% end %>
  </article> 
</section>

app/views/layouts/_footer.html.erb
<footer id="footer">
  &copy; Copyright Stephen Thomas 2012
</footer>

app/views/layouts/_header.html.erb
<header class="navHeader">
  <div class="content navContent">
    <a id="logo">ClutterBox</a>
    <nav>
      <ul>
        <li><%= link_to "Popular", popular_bookmarks_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
        <% if signed_in? %>
          <li><%= link_to "My Bookmarks",user_path(@current_user) %></li>
          <li><%= link_to "Account", edit_user_path(@current_user) %></li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Sign In", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clutter Box</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value) %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/public_pages/home.html.erb
<div id="home" class="center">
  <h1>
    ClutterBox
  </h1>
  <h2>
    A Collection For Everything Your Curious About
  </h2>
  <h3>
    <%= link_to "Sign Up Now!", signup_path %>
  </h2>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section>
    <% object.errors.full_messages.each do |msg| %>
      <article>* <%= msg %></article>
    <% end %>
  </section>
<% end %>

app/views/taggings/_tagging.html.erb
<span class="tag">
  <span>
    <%= link_to tagging.tag.name, tag_path(tagging.tag), class: "item" %>
    <% if current_user?(tagging.bookmark.user) %>
      <%= link_to "x", bookmark_tagging_path(tagging.bookmark_id, tagging.id), 
          method: :delete, class: "remove" %>
    <% end %>
  </span>
</span>

app/views/tags/_tag.html.erb
<span class="tag">
  <span>
    <%= link_to tag.name, tag_path(tag), class: "item" %>
  </span>
</span>

app/views/tags/index.html.erb
<h1>Tags</h1>
<section id="tag_index" class="tags center">
  <%= render @tags %>
</section>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<section id="tagged_feed" class="feed">
  <%= render partial: 'bookmarks/bookmark_item', collection: @bookmarks, :as => :bookmark %>
</section>

app/views/users/_user_fields.html.erb
<%= render 'shared/errors', object: f.object %>
<p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true %>
</p>
<p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true %>
</p>
<p>
  <%= f.label :username %>
  <%= f.text_field :username, required: true %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email, required: true %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password, required: true %>
</p>
<p>
  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation, required: true %>
</p>

app/views/users/edit.html.erb
<h1> Edit Account </h1>
<%= form_for(@user, html: { :class => "cbxForm center med"}) do |f| %>
  <%= render 'user_fields', f: f %>
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<h1> Users </h1>
<section id="users" class="feed">
  <% @users.each_with_index do |user, index| %>
    <article>
      <h3>
        <%= link_to user[:username], user_path(index) %>
      </h3>
      <div>      
        <%= link_to "Delete", user_path(index), method: :delete,
                    data: { confirm: "Are you sure you want to delete this user?" } %>
      </div>
    </article>
  <% end %>
</section>

app/views/users/new.html.erb
<h1> Create Account </h1>
<%= form_for(@user, html: { :class => "cbxForm center med"}) do |f| %>
  <%= render 'user_fields', f: f %>
  <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<div id="user_feed" class="center">
  <h1>
    <%= @user.username %>
  </h1>
  <dl id="profile">
    <dt>
       Name
    </dt>
    <dd>
      <%= @user.first_name + " " + @user.last_name %>
    </dd>
    <dt>
      Email
    </dt>
    <dd>
      <%= @user.email %>
    </dd>
  </dl>
  <div class="follow">
    <a href="joe_user/followers.html" > blank Followers </a>
    <a href="joe_user/followings.html" > Following blank </a>
  </div>
  <% if current_user?(@user) %>
    <h4 class="createB">
      <%= link_to "New Bookmark", new_bookmark_path %>
    </h4>
  <% end %>
  <section id="bookmarks" class="feed">
    <%= render @bookmarks %>
  </section>
</div>